config/routes.rb
Truxi::Application.routes.draw do
  resources :move_requests

  devise_for :users

  resources :movers

  match 'mover-signup' => 'welcome#mover_signup'
  match 'beta' => 'welcome#beta'
  root :to => "welcome#index"

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :address, presence:true
  geocoded_by :address
  after_validation :geocode
  acts_as_gmappable address: "address", process_geocoding: false
end

app/models/move_request.rb
class MoveRequest < ActiveRecord::Base
  belongs_to :origin, class_name: 'Location', dependent: :destroy
  belongs_to :destination, class_name: 'Location', dependent: :destroy
  accepts_nested_attributes_for :origin, :destination

  validates :origin, :destination, :date, presence: true
end

app/models/mover.rb
class Mover < ActiveRecord::Base
  belongs_to :user
  validates :user, :street_address, :city, :state, :zip, presence: true
  accepts_nested_attributes_for :user
  attr_accessor :distance

  geocoded_by :gmaps4rails_address
  after_validation :geocode
  acts_as_gmappable address: "street_address", process_geocoding: false

  def miles_away_from(object)
    return unless object && object.latitude && object.longitude
    self.distance_from([object.latitude, object.longitude])
  end

  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{street_address}\n #{city}, #{state} #{zip}" 
  end

  def gmaps4rails_infowindow
    "<b>#{user.name}</b><br/>#{street_address}<br />#{city}, #{state} #{zip}" 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_one :mover
  
  validates :name, :email, presence: true
  
  def is_mover?
    mover.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/move_requests_controller.rb
class MoveRequestsController < ApplicationController
 http_basic_authenticate_with :name => "truxi", :password => "optimus", except: :new 

  # GET /move_requests
  # GET /move_requests.json
  def index
    @move_requests = MoveRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @move_requests }
    end
  end

  # GET /move_requests/1
  # GET /move_requests/1.json
  def show
    @move_request = MoveRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @move_request }
    end
  end

  # GET /move_requests/new
  # GET /move_requests/new.json
  def new
    @move_request = MoveRequest.new(params[:move_request])
    @move_request.build_origin unless @move_request.origin
    @move_request.origin.address = 'Philadelphia, PA' unless @move_request.origin.address.present?
    @move_request.build_destination unless @move_request.destination
    if @move_request.origin
      @move_request.origin.geocode
      mover_letter = 'A'
      @movers = Mover.all.map {|m| m.distance = m.miles_away_from(@move_request.origin); m }.sort_by(&:distance)
      @marker_objs = @movers + [@move_request.origin]
      @markers = @marker_objs.to_gmaps4rails do |object, marker|
        if object.is_a?(Location)
          #marker.picture({picture: "http://maps.google.com/mapfiles/ms/micons/green.png"})
          marker.json({id: object.id})
        else
          marker.picture({picture: "http://www.google.com/mapfiles/marker#{mover_letter}.png"})
          marker.json({id: object.id}).tap do
            mover_letter = mover_letter.succ # Hacky
          end
        end
      end
      #@markers = [@move_request.origin].to_gmaps4rails do |location, marker|
        #marker.picture({
          #picture: "http://www.google.com/mapfiles/markerZ.png"
         #})
        #marker.json({id: location.id})
      #end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @move_request }
    end
  end

  # GET /move_requests/1/edit
  def edit
    @move_request = MoveRequest.find(params[:id])
  end

  # POST /move_requests
  # POST /move_requests.json
  def create
    @move_request = MoveRequest.new(params[:move_request])

    respond_to do |format|
      if @move_request.save
        format.html { redirect_to @move_request, notice: 'Move request was successfully created.' }
        format.json { render json: @move_request, status: :created, location: @move_request }
      else
        format.html { render action: "new" }
        format.json { render json: @move_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /move_requests/1
  # PUT /move_requests/1.json
  def update
    @move_request = MoveRequest.find(params[:id])

    respond_to do |format|
      if @move_request.update_attributes(params[:move_request])
        format.html { redirect_to @move_request, notice: 'Move request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @move_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /move_requests/1
  # DELETE /move_requests/1.json
  def destroy
    @move_request = MoveRequest.find(params[:id])
    @move_request.destroy

    respond_to do |format|
      format.html { redirect_to move_requests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movers_controller.rb
class MoversController < ApplicationController
 http_basic_authenticate_with :name => "truxi", :password => "optimus"
  #before_filter :authenticate_user!

  # GET /movers
  # GET /movers.json
  def index
    @movers = Mover.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movers }
    end
  end

  # GET /movers/1
  # GET /movers/1.json
  def show
    @mover = Mover.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mover }
    end
  end

  # GET /movers/new
  # GET /movers/new.json
  def new
    @mover = Mover.new
    @mover.build_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mover }
    end
  end

  # GET /movers/1/edit
  def edit
    @mover = Mover.find(params[:id])
  end

  # POST /movers
  # POST /movers.json
  def create
    @mover = Mover.new(params[:mover])

    respond_to do |format|
      if @mover.save
        format.html { redirect_to @mover, notice: 'Mover was successfully created.' }
        format.json { render json: @mover, status: :created, location: @mover }
      else
        format.html { render action: "new" }
        format.json { render json: @mover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movers/1
  # PUT /movers/1.json
  def update
    @mover = Mover.find(params[:id])

    respond_to do |format|
      if @mover.update_attributes(params[:mover])
        format.html { redirect_to @mover, notice: 'Mover was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movers/1
  # DELETE /movers/1.json
  def destroy
    @mover = Mover.find(params[:id])
    @mover.destroy

    respond_to do |format|
      format.html { redirect_to movers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @move_request = MoveRequest.new
    @move_request.build_origin
    @move_request.build_destination
  end

  def mover_signup
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/move_requests_helper.rb
module MoveRequestsHelper
end

app/helpers/movers_helper.rb
module MoversHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to(image_tag("logo.jpg"), root_path, class:'brand') %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li>
            <%= link_to('Edit account', edit_user_registration_path) %>
            </li>
          <% else %>
            <li>
            <%= link_to('Sign up', new_user_registration_path)  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truxi - Trucks in Your Pocket</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-345379-12']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
 <body>
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
        <div class="row">
          <div class="well">
            Truxi is a project for <a href="http://philly.startupweekend.org/">PHLSW 2012</a>. Photos, ratings and rates are for demonstration purposes only. <a href="/beta">Sign up</a> to find out when we launch</a>.
          </div>
        </div>
      </footer>
    </div> <!--! end of #container -->
    <%= yield :modals %>
    <%= yield :scripts %>
  </body>
</html>

app/views/move_requests/_form.html.erb
<%= simple_form_for(@move_request, html:{class:'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.simple_fields_for :origin do |origin_fields| %>
      <%= origin_fields.input :address, label:'Origin address' %>
    <%- end -%>
    <%= f.simple_fields_for :destination do |destination_fields| %>
      <%= destination_fields.input :address, label:'Destination address' %>
    <%- end -%>
    <%= f.input :date %>
    <%= f.input :time_frame %>
    <%= f.input :movers_needed %>
    <%= f.input :truck_size %>
    <%= f.input :description, hint: "Items to be moved, special instructions", input_html: {rows:3} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Back', move_requests_path, class:'btn' %>
  </div>
<% end %>

app/views/move_requests/_short_form.html.erb
    <%= simple_form_for(@move_request, url: new_move_request_path, method: :get, html: {class: "form-horizontal"}) do |f| %>
      <h3>Make Your Move</h3>
      <%= f.simple_fields_for :origin do |origin_fields| %>
        <%= origin_fields.input :address, label: "Origin", placeholder: "Philadelphia, PA" %>
      <%- end -%>
      <%= f.simple_fields_for :destination do |destination_fields| %>
        <%= destination_fields.input :address, label: "Destination", placeholder: "Philadelphia, PA" %>
      <%- end -%>
      <%= f.input :date %>
      <div class="control-group">
        <label class="control-label">Truck Size</label>
        <div class="controls">
          <div class="btn-group trucks" data-toggle="buttons-radio">
            <button class="btn"><i class="truck-pickup"></i></button>
            <button class="btn"><i class="truck-van"></i></button>
            <button class="btn"><i class="truck-box-sm"></i></button>
            <button class="btn"><i class="truck-box-md"></i></button>
            <button class="btn"><i class="truck-box-lg"></i></button>
          </div>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= f.submit "Search", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

app/views/move_requests/edit.html.erb
<h1>Editing move_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @move_request %> |
<%= link_to 'Back', move_requests_path %>

app/views/move_requests/index.html.erb
<h1>Listing move_requests</h1>

<table>
  <tr>
    <th>Destination</th>
    <th>Origin</th>
    <th>Date</th>
    <th>Time frame</th>
    <th>Movers needed</th>
    <th>Truck size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @move_requests.each do |move_request| %>
  <tr>
    <td><%= move_request.destination_id %></td>
    <td><%= move_request.origin_id %></td>
    <td><%= move_request.date %></td>
    <td><%= move_request.time_frame %></td>
    <td><%= move_request.movers_needed %></td>
    <td><%= move_request.truck_size %></td>
    <td><%= link_to 'Show', move_request %></td>
    <td><%= link_to 'Edit', edit_move_request_path(move_request) %></td>
    <td><%= link_to 'Destroy', move_request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Move request', new_move_request_path %>

app/views/move_requests/new.html.haml
%h1 Search for Movers

.well
  .row
    .span5
      = render 'short_form'
    .span6.relative.map
      = gmaps("markers" => {"data" => @markers}, map_options: {auto_zoom:false, zoom:11, auto_adjust:false, center_latitude: @move_request.origin.latitude, center_longitude: @move_request.origin.longitude})

.row
  .span12
    %h3 Select movers to contact:
    = simple_form_for(@move_request) do |f|
      %table.results.table.table-striped
        %thead
          %tr
            %th &nbsp;
            %th Photo
            %th Name
            %th City
            -if @move_request.origin.present?
              %th Distance
            %th Truck
            %th Hourly Rate
            %th Rating
            %th Description
        %tbody
          - letters = ('A'..'Z').to_a
          - @movers.each_with_index do |mover, index|
            %tr
              %td.select
                = label_tag "#{letters[index]}" do |t|
                  = check_box_tag "#{letters[index]}"
                  = letters[index]
              %td
                - if mover.photo.present?
                  = link_to(image_tag(mover.photo, size:"50x50"), "#photo_#{mover.id}", data:{toggle:'modal'})
                  - content_for :modals do
                    .modal.photo{id: "photo_#{mover.id}", style:'display:none;'}
                      = image_tag(mover.photo, size:"400x400")
              %td= mover.user.name
              %td= "#{mover.city.titleize}, #{mover.state.upcase}"
              -#
                %td= image_tag "truck-pics/#{mover.id % 11}.jpg"
              - if @move_request.origin.present?
                %td= sprintf("%.1f mi", mover.distance) if mover.distance
              %td 
                - truck = ["truck-pickup","truck-van","truck-box-sm", "truck-box-md", "truck-box-lg"].sample()
                %i{class: "#{truck}" }
              %td= number_to_currency(mover.hourly_rate)
              %td.stars
                - mover.rating.to_i.times do
                  %i.star-full>
                - (5 - mover.rating.to_i).times do
                  %i.star-empty>
              %td= truncate mover.description, length: 50, separator: ' '
      = link_to "Contact", '/beta', class: 'btn btn-primary btn-large'

app/views/move_requests/show.html.erb
<p>
  <b>Destination:</b>
  <%= @move_request.destination.address %>
</p>

<p>
  <b>Origin:</b>
  <%= @move_request.origin.address %>
</p>

<p>
  <b>Date:</b>
  <%= @move_request.date %>
</p>

<p>
  <b>Time frame:</b>
  <%= @move_request.time_frame %>
</p>

<p>
  <b>Movers needed:</b>
  <%= @move_request.movers_needed %>
</p>

<p>
  <b>Truck size:</b>
  <%= @move_request.truck_size %>
</p>


<%= link_to 'Edit', edit_move_request_path(@move_request) %> |
<%= link_to 'Back', move_requests_path %>

app/views/movers/_form.html.erb
<%= simple_form_for(@mover, html:{class:'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.simple_fields_for :user do |user_fields| %>
      <%= user_fields.input :name %>
      <%= user_fields.input :email %>
      <%= user_fields.input :password, as: :hidden, input_html:{value: 'abc123'} %>
    <%- end -%>
    <%= f.input :street_address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :hourly_rate %>
    <%= f.input :rating, as: :select, collection: 0..5 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary' %>
    <%= link_to 'Cancel', movers_path, class:'btn' %>
  </div>
<% end %>

app/views/movers/edit.html.erb
<h1>Editing mover</h1>

<%= render 'form' %>

<%= link_to 'Show', @mover %> |

app/views/movers/index.html.erb
<h1>Listing movers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile phone</th>
    <th>Description</th>
    <th>Hourly rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movers.each do |mover| %>
  <tr>
    <td><%= mover.user.name %></td>
    <td><%= mover.user.email %></td>
    <td><%= mover.user.mobile_phone %></td>
    <td><%= mover.description %></td>
    <td><%= mover.hourly_rate %></td>
    <td><%= link_to 'Show', mover %></td>
    <td><%= link_to 'Edit', edit_mover_path(mover) %></td>
    <td><%= link_to 'Destroy', mover, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mover', new_mover_path %>

app/views/movers/new.html.erb
<h1>Sign up as a mover</h1>

<%= render 'form' %>

app/views/movers/show.html.erb
<p>
  <b>Name:</b>
  <%= @mover.user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @mover.user.email %>
</p>

<p>
  <b>Mobile phone:</b>
  <%= @mover.user.mobile_phone %>
</p>

<p>
  <b>Address:</b>
  <%= simple_format @mover.gmaps4rails_address %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag @mover.photo if @mover.photo.present? %>
</p>

<p>
  <b>Description:</b>
  <%= @mover.description %>
</p>

<p>
  <b>Hourly rate:</b>
  <%= @mover.hourly_rate %>
</p>


<%= link_to 'Edit', edit_mover_path(@mover) %> |
<%= link_to 'Back', movers_path %>

app/views/welcome/beta.html.haml
%h1 Truxi is in Beta

%p Thanks for your interest in Truxi. We're still refining our business relationships with movers and collecting reliable data. In the meantime, please contact movers directly.

%h3 We look forward to simplifying your moving experience soon.

<div id="kickofflabs_embed_form"
data-landing_page_id="5887" 
data-signup_text="To be among the first to know when we launch, please provide your email address:"
data-placeholder_text="Type your email here..."
data-button_text="Subscribe"
data-share_text = "Share our site with your friends!"
data-influenced_count_text="Influenced so far:"
data-button_css_class="button btn btn-primary"
data-input_css_class="input"
data-promote_text="Check this out!"
data-error_message= "There was a problem with your email address!" 
></div>
<script src="//api.kickofflabs.com/embed/v1/embed.js" type="text/javascript"></script>

app/views/welcome/index.html.erb
<div class="row relative home">
  <div class="hero-unit clearfix">
    <div class="span5">
      <%= image_tag("truck_logo.png", class:'logo') %>
      <h1>Moving Power</h1>
      <h2>The fastest way to find a truck and a helping hand.</h2>
      <p>
        Truxi has ratings and prices from the big moving companies to the guy with a pickup down the street. Choose the service that fits you best.
      </p>
      <p><small>Are you a mover? <%= link_to "Sign up here", '/mover-signup' %>.</small></p>
    </div>

    <div class="span5 home-form">
      <%= render 'move_requests/short_form'  %> 
    </div>
  </div>
</div>
<div class="row">
  <h2>How does it work?</h2>
  <ol class="how-it-works">
    <li class="span4">
      Search for movers close to you.
      <p>Our database includes both moving companies and freelancers</p>
    </li>
    <li class="span4">
      Pick people to contact.
      <p>Ratings and up-front pricing helps you make a solid, quick decision.</p>
    </li>
    <li class="span4">
    Movers accept the job.
    <p>You then confirm your plans and pay for the move</p>
    </li>
  </ol>

</div>

app/views/welcome/mover_signup.html.haml
%h1 Mover Sign Up

%p Are you a moving company or a freelance mover? Get listed on Truxi!

%p
  = link_to "Email us", 'mailto:info@gettruxi.com'
  and we'll be in touch to get some more information.